import { Product, Banner } from '../types';
import haircareArganSerum from '../assets/images/haircare_argan_serum_1790644873315.jpg';
import haircareKeratinMask from '../assets/images/haircare_keratin_mask_1790644887080.jpg';
import haircareScalpShampoo from '../assets/images/haircare_scalp_shampoo_1790644900378.jpg';
import haircareBondRepair from '../assets/images/haircare_bond_repair_1790644917391.jpg';
import supercreamPedestal from '../assets/images/supercream_pedestal_1790160023057.jpg';
import theordinaryGlucosideTube from '../assets/images/theordinary_glucoside_tube_1790164428806.jpg';

export const HAIRCARE_PRODUCTS: Product[] = [
  {
    id: 'srm-hair-001',
    name: 'Moroccan Argan Oil & Keratin Frizz-Free Smoothing Hair Serum (100ml)',
    slug: 'moroccan-argan-oil-keratin-smoothing-hair-serum-100ml',
    brand: 'Moroccan Elixir Salon',
    category: 'Hair Care',
    subcategory: 'Hair Masks & Serums',
    price: 999,
    salePrice: 599,
    discountPercent: 40,
    rating: 4.9,
    reviewCount: 1240,
    images: [
      haircareArganSerum,
      supercreamPedestal,
      haircareBondRepair,
    ],
    stock: 145,
    sku: 'SRM-HAIR-ARG-599',
    sizes: ['100ml Glass Pump', '50ml Travel Size'],
    colors: [
      { name: 'Liquid Amber Gold', hex: '#D97706' },
    ],
    description: 'Salon-favorite anti-frizz smoothing hair serum formulated with pure cold-pressed Moroccan Argan Oil, hydrolyzed keratin proteins, and Vitamin E. Delivers 72-hour humidity and frizz control, restores silky mirror shine to dull strands, seals split ends, and provides heat defense against blow dryers and straighteners up to 230°C without leaving hair greasy.',
    specifications: {
      'Category': 'Hair Care · Hair Serum',
      'Price': '₹599 (Special Deal)',
      'Key Ingredients': 'Pure Moroccan Argan Oil, Hydrolyzed Keratin, Vitamin E (Tocopherol)',
      'Heat Protection': 'Guaranteed heat shielding up to 230°C / 450°F',
      'Frizz Control': '72-Hour humidity resistance, instant detangling',
      'Hair Type': 'Frizzy, dry, dull, chemically treated or color-treated hair',
      'Texture': 'Non-sticky, lightweight golden elixir with salon aroma',
      'Usage': 'Apply 2-3 pumps on damp or dry hair lengths and tips before styling',
      'Origin': 'Certified Salon Professional Grade',
    },
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-31T23:59:59',
    inStock: true,
    tags: [
      'hair care', 'hair serum', 'argan oil', 'keratin', 'frizz control',
      'heat protectant', 'hair repair', '500 to 800', 'trending', 'bestseller'
    ],
    returnDays: 14,
    warrantyInfo: '100% Genuine Salon Quality Assurance',
    isVisible: true,
    createdAt: '2026-09-24T12:00:00Z',
  },
  {
    id: 'srm-hair-002',
    name: 'Pilgrim Spanish Rosemary & 3% Redensyl Anti-Hairfall Stimulating Shampoo (300ml)',
    slug: 'pilgrim-rosemary-redensyl-anti-hairfall-shampoo-300ml',
    brand: 'Pilgrim Beauty Lab',
    category: 'Hair Care',
    subcategory: 'Shampoos',
    price: 799,
    salePrice: 549,
    discountPercent: 31,
    rating: 4.8,
    reviewCount: 960,
    images: [
      haircareScalpShampoo,
      theordinaryGlucosideTube,
      haircareArganSerum,
    ],
    stock: 210,
    sku: 'SRM-HAIR-RSM-549',
    sizes: ['300ml Pump Bottle'],
    colors: [
      { name: 'Botanical Herbal Gel', hex: '#15803D' },
    ],
    description: 'Sulfate-free clinical hair strengthening shampoo powered by pure Spanish Rosemary extract, 3% Redensyl, Biotin, and Plant Keratin. Cleanses scalp sebum plugs and heavy product build-up without stripping moisture, reactivates dormant hair follicles, reduces hair fall from roots by 85%, and builds bouncy, voluminous density.',
    specifications: {
      'Category': 'Hair Care · Anti-Hairfall Shampoo',
      'Price': '₹549',
      'Key Actives': 'Spanish Rosemary Oil, 3% Redensyl, Biotin (Vitamin B7), Plant Keratin',
      'Free From': 'Sulfates (SLS/SLES), Parabens, Phthalates, Mineral Oils',
      'Hair Fall Reduction': 'Clinically tested up to 85% reduced breakage in 4 weeks',
      'Scalp Type': 'Oily, thinning hair, itchy scalp, dandruff-prone',
      'Foam Quality': 'Gentle coconut-derived rich creamy lather',
      'Origin': 'Dermatologically Tested in India',
    },
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-31T23:59:59',
    inStock: true,
    tags: [
      'hair care', 'shampoo', 'rosemary shampoo', 'redensyl', 'biotin',
      'hair fall control', 'sulfate free', '500 to 800', 'trending'
    ],
    returnDays: 14,
    warrantyInfo: '100% Authentic Product Guarantee',
    isVisible: true,
    createdAt: '2026-09-24T12:05:00Z',
  },
  {
    id: 'srm-hair-003',
    name: "L'Oréal Professionnel Paris Pro-Keratin Deep Repair Conditioning Hair Mask (250g)",
    slug: 'loreal-professionnel-pro-keratin-deep-repair-hair-mask-250g',
    brand: "L'Oréal Professionnel Paris",
    category: 'Hair Care',
    subcategory: 'Hair Masks & Serums',
    price: 1050,
    salePrice: 699,
    discountPercent: 33,
    rating: 4.9,
    reviewCount: 1680,
    images: [
      haircareKeratinMask,
      supercreamPedestal,
      haircareBondRepair,
    ],
    stock: 130,
    sku: 'SRM-HAIR-MSK-699',
    sizes: ['250g Salon Tub', '500g Professional Tub'],
    colors: [
      { name: 'Whipped Keratin Cream', hex: '#FEF3C7' },
    ],
    description: "Professional salon-exclusive hair reconstruction spa treatment mask. Packed with high-potency Pro-Keratin complex, natural ceramides, and raw African Shea butter to replenish depleted protein bonds inside damaged hair cuticles. Eliminates dryness, restores elasticity, and transforms brittle, bleached, or heat-ravaged hair into soft, fluid silk in 5 minutes.",
    specifications: {
      'Category': 'Hair Care · Deep Conditioning Hair Mask',
      'Price': '₹699',
      'Key Active Complexes': 'Pro-Keratin Amino Acid Complex, Incell Ceramides, Raw Shea Butter',
      'Action Time': 'Deep nourishment in 3-5 minutes',
      'Target Concerns': 'Chemically damaged hair, split ends, color fade, extreme dryness',
      'Finish': 'Velvety fluid movement, mirror shine, zero weigh-down',
      'Origin': "L'Oréal Professionnel France / India Approved",
    },
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-31T23:59:59',
    inStock: true,
    tags: [
      'hair care', 'hair mask', 'keratin mask', 'hair spa', 'damaged hair repair',
      'deep conditioner', '500 to 800', 'trending', 'bestseller'
    ],
    returnDays: 14,
    warrantyInfo: '100% Genuine Salon Product Guarantee',
    isVisible: true,
    createdAt: '2026-09-24T12:10:00Z',
  },
  {
    id: 'srm-hair-004',
    name: 'Minimalist 18% Multi-Peptide & Redensyl Advanced Hair Density Scalp Serum (60ml)',
    slug: 'minimalist-multi-peptide-redensyl-hair-density-serum-60ml',
    brand: 'Minimalist Hair Science',
    category: 'Hair Care',
    subcategory: 'Hair Masks & Serums',
    price: 999,
    salePrice: 749,
    discountPercent: 25,
    rating: 4.9,
    reviewCount: 2150,
    images: [
      haircareArganSerum,
      haircareScalpShampoo,
      theordinaryGlucosideTube,
    ],
    stock: 190,
    sku: 'SRM-HAIR-PEP-749',
    sizes: ['60ml Dropper Bottle'],
    colors: [
      { name: 'Concentrated Scalp Drops', hex: '#FED7AA' },
    ],
    description: 'A powerful, science-backed concentrated scalp serum formulated with 5 proven hair growth actives in a total 18% multi-peptide blend: 3% Redensyl, 3% Procapil, 2% Anagain, 5% Baicapil, and 1% Caffeine. Clinical studies demonstrate noticeable new baby hairs and increased hair shaft thickness within 8 to 12 weeks of continuous nightly scalp application.',
    specifications: {
      'Category': 'Hair Care · Hair Density Serum',
      'Price': '₹749',
      'Active Ingredients': '3% Redensyl, 3% Procapil, 2% Anagain, 5% Baicapil, 1% Caffeine, Centella Extract',
      'Texture': 'Water-light transparent serum, absorbs instantly without oiliness',
      'Application': 'Apply 4-5 drops directly onto dry clean scalp nightly and massage',
      'Target Concerns': 'Hair thinning, receding hairline, low density, hormonal hair fall',
      'Origin': 'Minimalist Certified Labs India',
    },
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-31T23:59:59',
    inStock: true,
    tags: [
      'hair care', 'hair serum', 'hair growth', 'redensyl', 'peptides',
      'hair density', 'minimalist', '500 to 800', 'trending', 'bestseller'
    ],
    returnDays: 14,
    warrantyInfo: '100% Authentic Brand Sealed Package',
    isVisible: true,
    createdAt: '2026-09-24T12:15:00Z',
  },
  {
    id: 'srm-hair-005',
    name: 'Bare Anatomy Expert Plex Bond Repair Leave-In Conditioning Hair Cream (150ml)',
    slug: 'bare-anatomy-plex-bond-repair-leave-in-cream-150ml',
    brand: 'Bare Anatomy Expert',
    category: 'Hair Care',
    subcategory: 'Conditioners',
    price: 850,
    salePrice: 649,
    discountPercent: 24,
    rating: 4.8,
    reviewCount: 780,
    images: [
      haircareBondRepair,
      haircareKeratinMask,
      supercreamPedestal,
    ],
    stock: 165,
    sku: 'SRM-HAIR-BND-649',
    sizes: ['150ml Pump Bottle'],
    colors: [
      { name: 'Silken Pearl Cream', hex: '#F3F4F6' },
    ],
    description: 'Leave-in hair repair and styling cream formulated with Quadra-Plex technology that penetrates deep into hair cortex to reconnect broken disulfide bonds caused by bleaching, heat, and environmental stress. Smooths out frizzy cuticles, protects hair against up to 450°F thermal styling tools, and leaves lengths feeling weightlessly soft with bouncy movement.',
    specifications: {
      'Category': 'Hair Care · Leave-in Conditioner & Cream',
      'Price': '₹649',
      'Technology': 'Quadra-Plex Disulfide Bond Rebuilder & Amino Acid Complex',
      'Heat Shield': 'Protects hair against heat damage up to 450°F',
      'Benefits': 'Instant detangling, split end sealing, 48H frizz protection',
      'Hair Type': 'Wavy, curly, straight, bleached & heat-styled hair',
      'Origin': 'Dermatologically Tested · Made in India',
    },
    isTrending: false,
    isBestSeller: true,
    isNewArrival: true,
    isFlashDeal: false,
    inStock: true,
    tags: [
      'hair care', 'leave in conditioner', 'hair cream', 'bond repair',
      'heat protection', 'bare anatomy', '500 to 800'
    ],
    returnDays: 14,
    warrantyInfo: '100% Genuine Brand Assurance',
    isVisible: true,
    createdAt: '2026-09-24T12:20:00Z',
  },
  {
    id: 'srm-hair-006',
    name: 'OGX Whipped Virgin Coconut Milk & Japanese Tsubaki Camellia Conditioner (250ml)',
    slug: 'ogx-whipped-coconut-milk-tsubaki-conditioner-250ml',
    brand: 'OGX Salon Naturals',
    category: 'Hair Care',
    subcategory: 'Conditioners',
    price: 799,
    salePrice: 529,
    discountPercent: 34,
    rating: 4.8,
    reviewCount: 890,
    images: [
      haircareBondRepair,
      haircareKeratinMask,
      theordinaryGlucosideTube,
    ],
    stock: 140,
    sku: 'SRM-HAIR-OGX-529',
    sizes: ['250ml Bottle', '385ml Family Size'],
    colors: [
      { name: 'Coconut Milk White', hex: '#F8FAFC' },
    ],
    description: 'Nourishing, sulfate-free creamy conditioner whipped with organic Virgin Coconut Milk, Japanese Tsubaki Camellia Seed Oil, and ultra-hydrating silk peptides. Effortlessly glides across wet hair to melt away knots, infuses long-lasting hydration into dry and coarse textures, and delivers luxurious salon shine with a delicate tropical coconut aroma.',
    specifications: {
      'Category': 'Hair Care · Hydrating Conditioner',
      'Price': '₹529',
      'Key Ingredients': 'Whipped Coconut Milk, Japanese Tsubaki Camellia Oil, Silk Amino Peptides',
      'Free From': 'Sulfates, Microplastics, Harsh Dyes',
      'Texture': 'Rich creamy conditioner with effortless glide and slip',
      'Benefits': 'Restores elasticity, prevents split ends, silky softness',
      'Origin': '100% Authentic Imported Formula',
    },
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    isFlashDeal: false,
    inStock: true,
    tags: [
      'hair care', 'conditioner', 'coconut conditioner', 'ogx', 'silk peptides',
      'frizz control', '500 to 800'
    ],
    returnDays: 14,
    warrantyInfo: 'Original Authenticity Seal',
    isVisible: true,
    createdAt: '2026-09-24T12:25:00Z',
  },
  {
    id: 'srm-hair-007-botanical',
    name: 'Forest Essentials Ayurvedic Botanical Rosemary & Bhringraj Pre-Wash Scalp Oil (100ml)',
    slug: 'forest-essentials-rosemary-bhringraj-scalp-oil-100ml',
    brand: 'Forest Essentials Alchemy',
    category: 'Hair Care',
    subcategory: 'Hair Oils',
    price: 1100,
    salePrice: 789,
    discountPercent: 28,
    rating: 4.9,
    reviewCount: 650,
    images: [
      haircareArganSerum,
      haircareScalpShampoo,
      supercreamPedestal,
    ],
    stock: 115,
    sku: 'SRM-HAIR-FES-789',
    sizes: ['100ml Glass Bottle with Dropper'],
    colors: [
      { name: 'Herbal Emerald Gold', hex: '#CA8A04' },
    ],
    description: 'Authentic cold-pressed Ayurvedic pre-wash hair oil handcrafted with therapeutic herbs: Bhringraj (King of Hair), fresh Rosemary leaves, Indian Gooseberry (Amla), and Kalonji (Black Seed) slow-infused in organic Sweet Almond and Golden Jojoba oil. Nourishes deep scalp micro-vessels, controls flaky dandruff, arrests hair thinning, and encourages thick lustrous hair.',
    specifications: {
      'Category': 'Hair Care · Ayurvedic Hair Oil',
      'Price': '₹789',
      'Key Herbs': 'Bhringraj, Rosemary Leaf, Amla, Kalonji (Black Seed), Cold-Pressed Jojoba & Almond Oils',
      'Processing': 'Slow 30-day sunlight maceration method',
      'Application': 'Warm slightly, massage into scalp 1-2 hours prior to shampooing',
      'Benefits': 'Strengthens roots, soothes flaky scalp, prevents premature graying',
      'Origin': 'Handcrafted in Uttarakhand, India',
    },
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-31T23:59:59',
    inStock: true,
    tags: [
      'hair care', 'hair oil', 'bhringraj oil', 'rosemary oil', 'ayurvedic hair oil',
      'scalp oil', 'hair fall control', '500 to 800', 'trending'
    ],
    returnDays: 14,
    warrantyInfo: 'Certified 100% Natural Ayurvedic Ingredients',
    isVisible: true,
    createdAt: '2026-09-24T12:30:00Z',
  },
];

export const HAIRCARE_BANNER: Banner = {
  id: 'banner-hair-care',
  title: 'Salon Luxe Hair Care & Repair',
  subtitle: 'Moroccan Argan serums, Pro-Keratin repair masks, rosemary shampoos & scalp elixirs from ₹500 to ₹800.',
  tag: 'HAIR CARE SPECIAL · ₹500 - ₹800',
  ctaText: 'Shop Hair Care',
  ctaCategory: 'hair-care',
  image: haircareArganSerum,
  bgGradient: 'from-amber-950/85 via-orange-950/60 to-transparent',
  isActive: true,
};
