import { Product, Banner } from '../types';
import koreanCleanserGel from '../assets/images/korean_cleanser_gel_1790644195286.jpg';
import koreanSnailSerum from '../assets/images/korean_snail_serum_1790644209940.jpg';
import koreanRiceCream from '../assets/images/korean_rice_cream_1790644221762.jpg';
import koreanCicaSerum from '../assets/images/korean_cica_serum_1790644233167.jpg';
import koreanFoamCleanser from '../assets/images/korean_foam_cleanser_1790644245435.jpg';
import koreanWaterCream from '../assets/images/korean_water_cream_1790644259566.jpg';

// Supporting aesthetic texture and regimen shots
import theordinaryFoamMacro from '../assets/images/theordinary_foam_macro_1790164460569.jpg';
import theordinaryRegimenLayout from '../assets/images/theordinary_regimen_layout_1790164444941.jpg';
import theordinaryGlucosideTube from '../assets/images/theordinary_glucoside_tube_1790164428806.jpg';
import neutrogenaCleanserSplash from '../assets/images/neutrogena_cleanser_splash_1790156999435.jpg';
import supercreamJarSwatch from '../assets/images/supercream_jar_swatch_1790160007638.jpg';
import supercreamPedestal from '../assets/images/supercream_pedestal_1790160023057.jpg';
import supercreamTexture from '../assets/images/supercream_texture_1790160034661.jpg';
import himalayaSerumStone from '../assets/images/himalaya_serum_stone_1790158124270.jpg';
import dermacoTexturesFlatlay from '../assets/images/dermaco_textures_flatlay_1790161642637.jpg';

export const KOREAN_SKINCARE_PRODUCTS: Product[] = [
  // ==========================================
  // RANGE: ₹200 TO ₹500 (AND ₹300 TO ₹500)
  // ==========================================
  {
    id: 'srm-korean-005',
    name: 'Round Lab 1025 Dokdo Deep Sea Mineral Balancing Face Wash (150ml)',
    slug: 'round-lab-1025-dokdo-deep-sea-mineral-face-wash',
    brand: 'Round Lab',
    category: 'Skin Care',
    subcategory: 'Face Wash',
    price: 480,
    salePrice: 299,
    discountPercent: 38,
    rating: 4.9,
    reviewCount: 764,
    images: [
      koreanCleanserGel,
      theordinaryGlucosideTube,
      neutrogenaCleanserSplash,
    ],
    stock: 210,
    sku: 'KOR-RL-DKD-299',
    sizes: ['150ml Full Tube', '250ml Jumbo Pump'],
    colors: [
      { name: 'Pure Sea Foam', hex: '#BAE6FD' },
    ],
    description: 'Olive Young Korea #1 Best-Selling Cleansing Foam. Formulated with 72 concentrated natural minerals from deep sea water of Ulleungdo island, Panthenol, Allantoin, and Ceramide NP. Creates a rich, cushiony sub-acidic lather that melts away ultrafine dust, daily grime, and sunscreen residue without ever stripping skin moisture. Leaves your complexion calm, soft, and refreshed.',
    specifications: {
      'Category': 'Skin Care · Korean Face Wash',
      'Price': '₹299 (Special Deal)',
      'Product Type': 'Sub-acidic Mineral Facial Cleanser Foam',
      'Key Ingredients': 'Ulleungdo Deep Sea Water (72 minerals), Ceramide NP, Allantoin, Triple Hyaluronic Acid',
      'pH Balance': 'pH 5.0 - 6.0 (Optimal Skin-Friendly Acidic)',
      'Skin Type': 'Sensitive, Dry, Acne-Prone & Combination Skin',
      'Award': 'Olive Young Korea #1 Cleansing Foam Winner',
      'Texture': 'Dense marshmallow micro-foam with gentle glide',
      'Origin': 'Made in South Korea · 100% Genuine Certified',
    },
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-31T23:59:59',
    inStock: true,
    tags: [
      'korean', 'skin care', 'face wash', 'cleanser', 'round lab', 'dokdo',
      'deep sea water', 'sensitive skin', 'gentle face wash', '200 to 500', '300 to 500',
      'k-beauty', 'trending', 'bestseller'
    ],
    returnDays: 14,
    warrantyInfo: '100% Authentic Korean Skincare Guarantee',
    isVisible: true,
    createdAt: '2026-09-24T10:00:00Z',
  },
  {
    id: 'srm-korean-001',
    name: 'COSRX Low pH Good Morning Gentle Gel Face Wash Cleanser (50ml Travel & Daily Edition)',
    slug: 'cosrx-low-ph-good-morning-gel-cleanser-50ml',
    brand: 'COSRX',
    category: 'Skin Care',
    subcategory: 'Face Wash',
    price: 550,
    salePrice: 349,
    discountPercent: 36,
    rating: 4.9,
    reviewCount: 1420,
    images: [
      koreanCleanserGel,
      theordinaryFoamMacro,
      neutrogenaCleanserSplash,
    ],
    stock: 185,
    sku: 'KOR-CSRX-GEL-349',
    sizes: ['50ml Travel Edition', '150ml Standard Tube'],
    colors: [
      { name: 'Crystal Clear Gel', hex: '#E0F2FE' },
    ],
    description: 'The world-famous Korean morning face wash cleanser formulated at a skin-perfect slightly acidic pH of 5.0–6.0. Infused with natural purifying Tea Tree Leaf Oil and 0.5% BHA (Betaine Salicylate) to gently dissolve excess overnight sebum, unblock pores, and slough away dead skin cells without stripping your delicate barrier. Leaves skin feeling velvety soft, clear, and glowing.',
    specifications: {
      'Category': 'Skin Care · Korean Face Wash',
      'Price': '₹349',
      'Key Actives': 'Tea Tree Leaf Oil, 0.5% BHA (Betaine Salicylate), Evening Primrose Extract',
      'pH Balance': 'Skin-Friendly Low pH 5.3',
      'Skin Type': 'All Skin Types, Oily, Sensitive, Breakout-Prone',
      'Texture': 'Gentle foaming clear gel with natural herbal fragrance',
      'Free From': 'Parabens, Sulfates, Mineral Oils, Artificial Colorants',
      'Origin': 'Made in South Korea · 100% Genuine Guaranteed',
      'Usage': 'Apply onto wet face, gently massage, rinse with lukewarm water',
    },
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-31T23:59:59',
    inStock: true,
    tags: [
      'korean', 'skin care', 'face wash', 'cleanser', 'cosrx', 'gel cleanser',
      'low ph', 'tea tree', 'bha', 'acne care', 'glass skin', '300 to 500', '200 to 500',
      'k-beauty', 'trending', 'deal'
    ],
    returnDays: 14,
    warrantyInfo: '100% Authentic Korean Product Guarantee',
    isVisible: true,
    createdAt: '2026-09-24T10:05:00Z',
  },
  {
    id: 'srm-korean-003',
    name: 'Anua Heartleaf Quercetinol Pore Deep Cleansing Foam Face Wash (150ml)',
    slug: 'anua-heartleaf-quercetinol-pore-deep-cleansing-foam-face-wash',
    brand: 'Anua',
    category: 'Skin Care',
    subcategory: 'Face Wash',
    price: 599,
    salePrice: 399,
    discountPercent: 33,
    rating: 4.8,
    reviewCount: 1120,
    images: [
      koreanFoamCleanser,
      theordinaryFoamMacro,
      koreanCleanserGel,
    ],
    stock: 220,
    sku: 'KOR-ANUA-WSH-399',
    sizes: ['150ml Tube'],
    colors: [
      { name: 'Sage Cloud Foam', hex: '#84CC16' },
    ],
    description: 'Enriched with 3,000ppm finely milled Houttuynia Cordata (Heartleaf) powder and pure Quercetinol extracted directly from heartleaf blooms, this viral Korean pore face wash creates a luxurious micro-bubble lather that penetrates deep into pores to draw out stubborn blackheads, excess sebum, and makeup remnants while soothing sensitive, irritated skin.',
    specifications: {
      'Category': 'Skin Care · Korean Face Wash',
      'Price': '₹399',
      'Key Ingredients': 'Heartleaf Powder (3,000ppm), Quercetinol, 8-Hyaluronic Complex, BHA',
      'Micro-Bubble Tech': 'Dense cloud whipped lather for 0.05mm deep pore penetration',
      'Skin Type': 'Pore-congested, Blackhead-prone, Oily & Combination skin',
      'Benefits': 'Exfoliates dead skin, controls sebum by 48%, calms inflammation',
      'Origin': 'South Korea · 100% Genuine',
    },
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-31T23:59:59',
    inStock: true,
    tags: [
      'korean', 'skin care', 'face wash', 'cleanser', 'anua', 'heartleaf',
      'pore cleanser', 'foam wash', 'blackhead removal', '300 to 500', '200 to 500',
      'k-beauty', 'trending'
    ],
    returnDays: 14,
    warrantyInfo: '100% Original Brand Verification Seal',
    isVisible: true,
    createdAt: '2026-09-24T10:10:00Z',
  },
  {
    id: 'srm-korean-002',
    name: 'Beauty of Joseon Calming Glow Face Serum (Green Tea + Panthenol 30ml)',
    slug: 'beauty-of-joseon-calming-glow-face-serum-green-tea-panthenol',
    brand: 'Beauty of Joseon',
    category: 'Skin Care',
    subcategory: 'Serums & Essences',
    price: 699,
    salePrice: 449,
    discountPercent: 35,
    rating: 4.9,
    reviewCount: 980,
    images: [
      koreanCicaSerum,
      himalayaSerumStone,
      theordinaryRegimenLayout,
    ],
    stock: 140,
    sku: 'KOR-BOJ-CLM-449',
    sizes: ['30ml Dropper Bottle'],
    colors: [
      { name: 'Botanical Amber Essence', hex: '#D97706' },
    ],
    description: 'Enriched with traditional Korean Hanbang herbal medicine, this soothing face serum (sirum) blends 76% Camellia Sinensis (Green Tea) Leaf Water and 2% Panthenol (Vitamin B5). It rapidly pacifies irritated, red, or sun-stressed skin, reinforces moisture barrier defense, and imparts an unmistakable dewy Korean glass-skin luminosity without any greasy residue.',
    specifications: {
      'Category': 'Skin Care · Korean Face Serum / Sirum',
      'Price': '₹449',
      'Key Ingredients': '76% Green Tea Leaf Water, 2% Panthenol (Pro-Vitamin B5), Centella Asiatica, Artemisia',
      'Skin Type': 'Sensitive, Dehydrated, Redness-Prone, Normal to Oily',
      'Texture': 'Silky, water-burst fast-absorbing serum drop',
      'Free From': 'Artificial Fragrance, Essential Oils, Parabens, Alcohol',
      'Origin': 'Made in Seoul, South Korea · 100% Genuine',
      'Routine Step': 'Apply 2-3 drops after cleansing/toning both AM & PM',
    },
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-31T23:59:59',
    inStock: true,
    tags: [
      'korean', 'skin care', 'serum', 'sirum', 'beauty of joseon', 'green tea',
      'panthenol', 'cica', 'glow', 'soothing', 'glass skin', '300 to 500', '200 to 500',
      'k-beauty'
    ],
    returnDays: 14,
    warrantyInfo: 'Authentic Korean Beauty Certified',
    isVisible: true,
    createdAt: '2026-09-24T10:15:00Z',
  },
  {
    id: 'srm-korean-004',
    name: 'Innisfree Green Tea Seed Hyaluronic Moisture Barrier Face Cream (50ml)',
    slug: 'innisfree-green-tea-seed-hyaluronic-barrier-face-cream',
    brand: 'Innisfree',
    category: 'Skin Care',
    subcategory: 'Moisturizers & Creams',
    price: 650,
    salePrice: 469,
    discountPercent: 28,
    rating: 4.8,
    reviewCount: 830,
    images: [
      koreanWaterCream,
      supercreamJarSwatch,
      supercreamTexture,
    ],
    stock: 160,
    sku: 'KOR-INNI-CRM-469',
    sizes: ['50ml Jar'],
    colors: [
      { name: 'Fresh Dew Cream', hex: '#6EE7B7' },
    ],
    description: 'Formulated with organic Beauty Green Tea™ freshly harvested from Jeju Island and encapsulated 5-layer Nano Hyaluronic Acid, this weightless daily moisturizing face cream (creem) seals intense hydration into deep skin layers for up to 72 hours. Ceramide NP and squalane reinforce damaged moisture barriers against dry weather and pollution.',
    specifications: {
      'Category': 'Skin Care · Korean Face Cream / Creem',
      'Price': '₹469',
      'Key Ingredients': 'Jeju Beauty Green Tea™, 5 types of Hyaluronic Acid, Ceramide NP, Squalane',
      'Texture': 'Lightweight whipped pudding gel-cream that melts into skin',
      'Hydration Duration': 'Up to 72 hours continuous moisture retention',
      'Skin Type': 'All skin types, normal, dry, combination & dull skin',
      'Finish': 'Dewy, non-greasy Korean natural glass-glow',
      'Origin': 'Jeju Island, South Korea',
    },
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-31T23:59:59',
    inStock: true,
    tags: [
      'korean', 'skin care', 'cream', 'creem', 'moisturizer', 'innisfree',
      'green tea', 'hyaluronic acid', 'ceramide', 'barrier cream', '300 to 500', '200 to 500',
      'k-beauty'
    ],
    returnDays: 14,
    warrantyInfo: '100% Original Korean Product Guarantee',
    isVisible: true,
    createdAt: '2026-09-24T10:20:00Z',
  },
  {
    id: 'srm-korean-011',
    name: 'Round Lab Inje Birch Juice Moisturizing Face Cream (40ml Travel Tube)',
    slug: 'round-lab-birch-juice-moisturizing-face-cream-40ml',
    brand: 'Round Lab',
    category: 'Skin Care',
    subcategory: 'Moisturizers & Creams',
    price: 650,
    salePrice: 479,
    discountPercent: 26,
    rating: 4.8,
    reviewCount: 590,
    images: [
      koreanWaterCream,
      supercreamTexture,
      theordinaryGlucosideTube,
    ],
    stock: 180,
    sku: 'KOR-RL-BJC-479',
    sizes: ['40ml Tube'],
    colors: [
      { name: 'Birch Dew Gel', hex: '#E0F2FE' },
    ],
    description: 'Enriched with pure Birch Tree sap harvested from the cool highland forests of Inje, South Korea. Loaded with 17 amino acids, minerals, and Vita Hyaluronic Acid micro-capsule beads that burst on contact to drench thirsty skin in cooling, weightless hydration. Perfect under makeup as a priming moisturizer or as an all-night hydration barrier.',
    specifications: {
      'Category': 'Skin Care · Korean Face Cream / Creem',
      'Price': '₹479',
      'Key Ingredients': 'Inje Birch Tree Sap, Vita Hyaluronic Acid, Jojoba Esters, Panthenol',
      'Texture': 'Watery cooling gel-cream with bursting hydration beads',
      'Skin Type': 'Dehydrated oily, combination, normal & sensitive skin',
      'Origin': 'South Korea · 100% Genuine',
    },
    isTrending: false,
    isBestSeller: true,
    isNewArrival: true,
    isFlashDeal: false,
    inStock: true,
    tags: [
      'korean', 'skin care', 'cream', 'creem', 'moisturizer', 'round lab',
      'birch juice', 'cooling cream', '300 to 500', '200 to 500', 'k-beauty'
    ],
    returnDays: 14,
    warrantyInfo: 'Authentic Korean Skincare Seal',
    isVisible: true,
    createdAt: '2026-09-24T10:25:00Z',
  },

  // ==========================================
  // RANGE: ₹500 TO ₹900
  // ==========================================
  {
    id: 'srm-korean-008',
    name: 'Haruharu Wonder Black Rice Moisture 5.5 Soft Cleansing Gel Face Wash (150ml)',
    slug: 'haruharu-wonder-black-rice-soft-cleansing-gel-face-wash',
    brand: 'Haruharu Wonder',
    category: 'Skin Care',
    subcategory: 'Face Wash',
    price: 850,
    salePrice: 579,
    discountPercent: 32,
    rating: 4.8,
    reviewCount: 640,
    images: [
      koreanCleanserGel,
      neutrogenaCleanserSplash,
      theordinaryFoamMacro,
    ],
    stock: 135,
    sku: 'KOR-HHW-WSH-579',
    sizes: ['150ml Bottle with Pump'],
    colors: [
      { name: 'Fermented Rice Gel', hex: '#EDE9FE' },
    ],
    description: 'An ultra-gentle, 100% vegan Korean face wash formulated at skin-balancing pH 5.5. Features 100% locally harvested fermented Korean Black Rice extract rich in protective polyphenols and anthocyanin antioxidants, fermented bamboo shoot bark, and plant-derived coconut surfactants. Effortlessly lifts away sunscreen, makeup, and pollution while infusing hydrating moisture.',
    specifications: {
      'Category': 'Skin Care · Korean Face Wash',
      'Price': '₹579',
      'Key Ingredients': 'Fermented Korean Black Rice Extract, Bamboo Shoot Bark, Beta-Glucan, Trehalose',
      'Formula': '100% Fragrance-Free, Essential Oil-Free, Vegan & EWG Green Verified',
      'Skin Type': 'All skin types, highly sensitive, rosacea-prone & dry skin',
      'Packaging': 'Sustainable recyclable bottle with precision lock pump',
      'Origin': 'South Korea · 100% Authentic',
    },
    isTrending: false,
    isBestSeller: true,
    isNewArrival: true,
    isFlashDeal: false,
    inStock: true,
    tags: [
      'korean', 'skin care', 'face wash', 'cleanser', 'haruharu wonder', 'black rice',
      'gel cleanser', 'unscented', 'vegan', '500 to 900', 'k-beauty'
    ],
    returnDays: 14,
    warrantyInfo: 'Authentic Korean Beauty Certified',
    isVisible: true,
    createdAt: '2026-09-24T10:30:00Z',
  },
  {
    id: 'srm-korean-010',
    name: 'SKIN1004 Madagascar Centella Asiatica 100% Calming Face Serum Ampoule (55ml)',
    slug: 'skin1004-madagascar-centella-asiatica-calming-serum-ampoule',
    brand: 'SKIN1004',
    category: 'Skin Care',
    subcategory: 'Serums & Essences',
    price: 890,
    salePrice: 629,
    discountPercent: 29,
    rating: 4.9,
    reviewCount: 1670,
    images: [
      koreanCicaSerum,
      theordinaryRegimenLayout,
      himalayaSerumStone,
    ],
    stock: 240,
    sku: 'KOR-SKN-CTA-629',
    sizes: ['55ml Dropper Flask', '100ml Jumbo Dropper'],
    colors: [
      { name: 'Golden Cica Nectar', hex: '#F59E0B' },
    ],
    description: 'Crafted with 100% pure Centella Asiatica extract sustainably harvested from the untouched high-altitude habitats of Madagascar. This iconic Korean golden serum (sirum) instantly extinguishes facial heat, inflammation, redness, and active acne breakouts. Its non-sticky watery texture penetrates instantly to repair skin barrier integrity and deliver a crystal-clear radiant glass finish.',
    specifications: {
      'Category': 'Skin Care · Korean Face Serum / Sirum',
      'Price': '₹629',
      'Key Active': '100% Pure Centella Asiatica Extract (Asiaticoside, Madecassic Acid, Asiatic Acid)',
      'Texture': 'Light watery golden serum, zero stickiness, instant absorption',
      'Skin Type': 'Acne-prone, Redness, Rosacea, Sensitive, Oily & Stressed skin',
      'Benefits': 'Calms cystic blemishes, heals damaged barrier, refines pores, fades acne marks',
      'Origin': 'Made in South Korea · 100% Genuine Certified',
    },
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-31T23:59:59',
    inStock: true,
    tags: [
      'korean', 'skin care', 'serum', 'sirum', 'skin1004', 'centella', 'cica',
      'ampoule', 'calming', 'acne blemish', 'glass skin', '500 to 900', 'k-beauty', 'trending'
    ],
    returnDays: 14,
    warrantyInfo: '100% Genuine Brand Authenticity Guarantee',
    isVisible: true,
    createdAt: '2026-09-24T10:35:00Z',
  },
  {
    id: 'srm-korean-007',
    name: 'Beauty of Joseon Dynasty Rice Bran & Ceramide Radiance Face Cream (50ml)',
    slug: 'beauty-of-joseon-dynasty-rice-ceramide-face-cream',
    brand: 'Beauty of Joseon',
    category: 'Skin Care',
    subcategory: 'Moisturizers & Creams',
    price: 950,
    salePrice: 699,
    discountPercent: 26,
    rating: 4.9,
    reviewCount: 1850,
    images: [
      koreanRiceCream,
      supercreamPedestal,
      supercreamTexture,
    ],
    stock: 195,
    sku: 'KOR-BOJ-DYN-699',
    sizes: ['50ml Frosted Glass Jar'],
    colors: [
      { name: 'Royal Rice Pearl', hex: '#FDFBF7' },
    ],
    description: 'Inspired by ancient royal skincare secrets documented in the Joseon Dynasty medicinal encyclopedia, this luxurious face cream (creem) combines 29% Rice Bran Water, 5% Ginseng Root Water, 2% Niacinamide, Squalane, and 3-Ceramide lipid complexes. Delivers deep velvety nourishment, illuminates dull skin tone, tightens elasticity, and imparts a silky porcelain Korean glass glow.',
    specifications: {
      'Category': 'Skin Care · Korean Face Cream / Creem',
      'Price': '₹699',
      'Key Ingredients': '29% Rice Bran Water, 5% Ginseng Root Extract, 2% Niacinamide, Squalane, Ceramide NP',
      'Texture': 'Silky whipped custard cream that absorbs seamlessly with zero greasiness',
      'Skin Type': 'Normal, Dry, Combination, Sensitive & Mature Skin',
      'Benefits': 'Profound barrier hydration, brightening, elasticity boost, porcelain radiance',
      'Origin': 'Seoul, South Korea · 100% Genuine',
    },
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-31T23:59:59',
    inStock: true,
    tags: [
      'korean', 'skin care', 'cream', 'creem', 'beauty of joseon', 'rice cream',
      'ceramide', 'niacinamide', 'glow cream', 'glass skin', '500 to 900', 'k-beauty', 'trending'
    ],
    returnDays: 14,
    warrantyInfo: 'Authentic Korean Beauty Certified',
    isVisible: true,
    createdAt: '2026-09-24T10:40:00Z',
  },
  {
    id: 'srm-korean-006',
    name: 'COSRX Advanced Snail 96 Mucin Power Essence & Hydrating Face Serum (100ml)',
    slug: 'cosrx-advanced-snail-96-mucin-power-essence-serum-100ml',
    brand: 'COSRX',
    category: 'Skin Care',
    subcategory: 'Serums & Essences',
    price: 1050,
    salePrice: 749,
    discountPercent: 29,
    rating: 5.0,
    reviewCount: 3890,
    images: [
      koreanSnailSerum,
      supercreamJarSwatch,
      dermacoTexturesFlatlay,
    ],
    stock: 310,
    sku: 'KOR-CSRX-SNL-749',
    sizes: ['100ml Pump Bottle'],
    colors: [
      { name: 'Luminous Dew Essence', hex: '#FEF08A' },
    ],
    description: 'The undisputed global Holy Grail of Korean Glass Skin. Packed with 96.3% Snail Secretion Filtrate, this concentrated serum essence hydrates, repairs damaged skin barriers, fades stubborn acne scars and hyperpigmentation, smooths uneven skin texture, and locks in plump, juicy moisture all day. 100% cruelty-free, safe extraction without harming snails.',
    specifications: {
      'Category': 'Skin Care · Korean Face Serum / Sirum',
      'Price': '₹749',
      'Key Active': '96.3% Snail Secretion Filtrate, 1,000ppm Sodium Hyaluronate, Panthenol, Allantoin',
      'Texture': 'Lush, slippery, fast-absorbing hydrating essence, non-sticky on drydown',
      'Target Concerns': 'Dehydration, dullness, acne scarring, rough texture, compromised barrier',
      'Safety': '100% Cruelty-Free, Dermatologist Approved, Hypoallergenic',
      'Origin': 'Made in South Korea · 100% Genuine Guaranteed',
    },
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-31T23:59:59',
    inStock: true,
    tags: [
      'korean', 'skin care', 'serum', 'sirum', 'snail mucin', 'cosrx',
      'glass skin', 'acne scars', 'hydration', '500 to 900', 'k-beauty', 'trending', 'bestseller'
    ],
    returnDays: 14,
    warrantyInfo: '100% Certified Genuine COSRX Korea',
    isVisible: true,
    createdAt: '2026-09-24T10:45:00Z',
  },
  {
    id: 'srm-korean-012',
    name: 'Dear Klairs Rich Moist Soothing Daily Face Cream (60ml Easy-Squeeze Tube)',
    slug: 'dear-klairs-rich-moist-soothing-daily-face-cream',
    brand: 'Dear, Klairs',
    category: 'Skin Care',
    subcategory: 'Moisturizers & Creams',
    price: 1090,
    salePrice: 799,
    discountPercent: 27,
    rating: 4.9,
    reviewCount: 1180,
    images: [
      koreanRiceCream,
      supercreamPedestal,
      theordinaryGlucosideTube,
    ],
    stock: 155,
    sku: 'KOR-KLR-RMS-799',
    sizes: ['60ml Easy-Squeeze Tube'],
    colors: [
      { name: 'Soothing White Silk', hex: '#FAF5FF' },
    ],
    description: 'A round-the-year rescue face cream (creem) specifically crafted for delicate, reactive skin. Formulated with plant-derived yeast Beta-Glucan, Ceramide NP, Centella Asiatica, and Jojoba Oil. Features an immediate thermal soothing effect that cools skin temperature, calms flaking redness, and rebuilds the protective lipid barrier against environmental stress.',
    specifications: {
      'Category': 'Skin Care · Korean Face Cream / Creem',
      'Price': '₹799',
      'Key Ingredients': 'Beta-Glucan, Ceramide NP, Centella Asiatica, Shea Butter, Tocopheryl Acetate',
      'Texture': 'Rich velvety comforting cream that absorbs without tackiness',
      'Certifications': 'PETA-Approved Cruelty-Free & Vegan, Fragrance-Free',
      'Skin Type': 'Sensitive, Dry, Stressed, Redness-Prone skin',
      'Origin': 'Seoul, South Korea · 100% Genuine',
    },
    isTrending: false,
    isBestSeller: true,
    isNewArrival: true,
    isFlashDeal: false,
    inStock: true,
    tags: [
      'korean', 'skin care', 'cream', 'creem', 'moisturizer', 'klairs',
      'rich moist', 'beta glucan', 'soothing', '500 to 900', 'k-beauty'
    ],
    returnDays: 14,
    warrantyInfo: '100% Original Korean Product Guarantee',
    isVisible: true,
    createdAt: '2026-09-24T10:50:00Z',
  },
  {
    id: 'srm-korean-009',
    name: 'Laneige Water Bank Blue Hyaluronic Intensive Moisture Barrier Face Cream (50ml)',
    slug: 'laneige-water-bank-blue-hyaluronic-moisture-barrier-cream',
    brand: 'Laneige',
    category: 'Skin Care',
    subcategory: 'Moisturizers & Creams',
    price: 1199,
    salePrice: 849,
    discountPercent: 29,
    rating: 4.9,
    reviewCount: 2480,
    images: [
      koreanWaterCream,
      supercreamPedestal,
      supercreamJarSwatch,
    ],
    stock: 170,
    sku: 'KOR-LNG-WB-849',
    sizes: ['50ml Refillable Pod Jar'],
    colors: [
      { name: 'Blue Aqua Gel', hex: '#38BDF8' },
    ],
    description: 'Prestige Korean moisturizing face cream (creem) powered by patented micro-sized Blue Hyaluronic Acid that is 2,000x smaller for 300% faster skin penetration. Clinically proven to repair damaged moisture barrier by 62% in just 1 hour and deliver up to 100 hours of continuous deep hydration. Melt-in rich formula strengthens and soothes sensitized, flaky skin.',
    specifications: {
      'Category': 'Skin Care · Korean Face Cream / Creem',
      'Price': '₹849',
      'Key Technology': 'Patented Micro Blue Hyaluronic Acid (Fermented 10-step process), Pepta-panthenol',
      'Barrier Repair': 'Clinically proven 62.2% barrier repair within 60 minutes',
      'Hydration Longevity': 'Up to 100 hours deep moisture retention',
      'Skin Type': 'Normal, Dry, Flaky, Stressed, Dehydrated skin',
      'Origin': 'Amorepacific Seoul, South Korea · 100% Genuine',
    },
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-31T23:59:59',
    inStock: true,
    tags: [
      'korean', 'skin care', 'cream', 'creem', 'moisturizer', 'laneige',
      'water bank', 'blue hyaluronic', 'barrier repair', '500 to 900', 'k-beauty', 'trending'
    ],
    returnDays: 14,
    warrantyInfo: '100% Certified Authentic Laneige Korea',
    isVisible: true,
    createdAt: '2026-09-24T10:55:00Z',
  },
];

export const KOREAN_SKINCARE_BANNER: Banner = {
  id: 'banner-korean-skincare',
  title: 'Korean Glass Skin & K-Beauty Edit',
  subtitle: 'Authentic Korean face wash, snail mucin serums, centella ampoules & hydrating creams from ₹299 to ₹849.',
  tag: 'K-BEAUTY SPECIAL · ₹299 - ₹849',
  ctaText: 'Shop Korean Skincare',
  ctaCategory: 'skin-care',
  image: koreanSnailSerum,
  bgGradient: 'from-emerald-950/85 via-teal-950/60 to-transparent',
  isActive: true,
};
